/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.spotifei.Views.Panels.Artist;

import net.spotifei.Controller.ArtistController;
import net.spotifei.Infrastructure.Container.AppContext;
import net.spotifei.Views.MainFrame;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;

/**
 *
 * @author fengl
 */
public class RegisterMusicPanel extends JPanel {

    private final MainFrame mainframe;
    private final AppContext appContext;
    private final ArtistController artistController;

    public RegisterMusicPanel(MainFrame mainframe, AppContext appContext) {
        this.appContext = appContext;
        this.mainframe = mainframe;
        this.artistController = appContext.getArtistController(this, mainframe);
        initComponents();
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JButton getBt_salvar() {
        return bt_salvar;
    }

    public void setBt_salvar(JButton bt_salvar) {
        this.bt_salvar = bt_salvar;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JTextField getTxt_genero_musicacad() {
        return txt_genero_musicacad;
    }

    public void setTxt_genero_musicacad(JTextField txt_genero_musicacad) {
        this.txt_genero_musicacad = txt_genero_musicacad;
    }

    public JTextField getTxt_nome_musicacad() {
        return txt_nome_musicacad;
    }

    public void setTxt_nome_musicacad(JTextField txt_nome_musicacad) {
        this.txt_nome_musicacad = txt_nome_musicacad;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel1.setAlignmentX(Component.CENTER_ALIGNMENT);

        jLabel2 = new JLabel();
        jLabel2.setAlignmentX(Component.CENTER_ALIGNMENT);

        jLabel4 = new JLabel();
        jLabel4.setAlignmentX(Component.CENTER_ALIGNMENT);

        txt_nome_musicacad = new JTextField();
        txt_nome_musicacad.setMinimumSize(new Dimension(300, 30));
        txt_nome_musicacad.setPreferredSize(new Dimension(300, 30));
        txt_nome_musicacad.setMaximumSize(new Dimension(300, 30));
        txt_nome_musicacad.setAlignmentX(Component.CENTER_ALIGNMENT);

        txt_genero_musicacad = new JTextField();
        txt_genero_musicacad.setMinimumSize(new Dimension(300, 30));
        txt_genero_musicacad.setPreferredSize(new Dimension(300, 30));
        txt_genero_musicacad.setMaximumSize(new Dimension(300, 30));
        txt_genero_musicacad.setAlignmentX(Component.CENTER_ALIGNMENT);

        bt_salvar = new JButton();
        bt_salvar.setAlignmentX(Component.CENTER_ALIGNMENT);

        jLabel5 = new JLabel();
        jLabel5.setAlignmentX(Component.CENTER_ALIGNMENT);

        bt_selecionar_musica = new JButton();
        bt_selecionar_musica.setAlignmentX(Component.CENTER_ALIGNMENT);

        setBackground(new java.awt.Color(35, 35, 35));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("REGISTRAR MÚSICAS");


        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Genero:");

        bt_salvar.setBackground(new java.awt.Color(0, 109, 170));
        bt_salvar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_salvar.setForeground(new java.awt.Color(0, 0, 0));
        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Música:");

        bt_selecionar_musica.setText("Selecionar a música");
        bt_selecionar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selecionar_musicaActionPerformed(evt);
            }
        });

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        JPanel nameWrapper = new JPanel();
        nameWrapper.setLayout(new BoxLayout(nameWrapper, BoxLayout.X_AXIS));
        nameWrapper.setBorder(null);
        nameWrapper.setMaximumSize(new Dimension(400, 30));
        nameWrapper.setOpaque(false);

        nameWrapper.add(jLabel2);
        nameWrapper.add(Box.createHorizontalStrut(10));
        nameWrapper.add(txt_nome_musicacad);

        JPanel genreWrapper = new JPanel();
        genreWrapper.setLayout(new BoxLayout(genreWrapper, BoxLayout.X_AXIS));
        genreWrapper.setBorder(null);
        genreWrapper.setMaximumSize(new Dimension(400, 30));
        genreWrapper.setOpaque(false);

        genreWrapper.add(jLabel4);
        genreWrapper.add(Box.createHorizontalStrut(10));
        genreWrapper.add(txt_genero_musicacad);

        JPanel musicWrapper = new JPanel();
        musicWrapper.setLayout(new BoxLayout(musicWrapper, BoxLayout.X_AXIS));
        musicWrapper.setBorder(null);
        musicWrapper.setMaximumSize(new Dimension(400, 30));
        musicWrapper.setOpaque(false);

        musicWrapper.add(jLabel5);
        musicWrapper.add(Box.createHorizontalStrut(10));
        musicWrapper.add(bt_selecionar_musica);

        this.add(jLabel1);
        this.add(Box.createVerticalStrut(150));
        this.add(nameWrapper);
        this.add(Box.createVerticalStrut(10));
        this.add(genreWrapper);
        this.add(Box.createVerticalStrut(10));
        this.add(musicWrapper);
        this.add(Box.createVerticalStrut(50));
        this.add(bt_salvar);

    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        artistController.registerMusic();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_selecionar_musicaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos .opus", "opus");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            musicFilePath = fileChooser.getSelectedFile().getAbsolutePath();
            bt_selecionar_musica.setText(musicFilePath);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private String musicFilePath;
    private JButton bt_salvar;
    private JButton bt_selecionar_musica;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JTextField txt_genero_musicacad;
    private JTextField txt_nome_musicacad;
    // End of variables declaration//GEN-END:variables


    public String getMusicFilePath() {
        return musicFilePath;
    }


}
