/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.spotifei.Views.Panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import net.spotifei.Views.MainFrame;

public class ADMSistemaPanel extends javax.swing.JPanel {

    private final MainFrame mainframe;
    
    public ADMSistemaPanel(MainFrame mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }

    public JButton getBt_top5mais() {
        return bt_top5mais;
    }

    public void setBt_top5mais(JButton bt_top5mais) {
        this.bt_top5mais = bt_top5mais;
    }

    public JButton getBt_top5menos() {
        return bt_top5menos;
    }

    public void setBt_top5menos(JButton bt_top5menos) {
        this.bt_top5menos = bt_top5menos;
    }

    public JButton getBt_total_musicas() {
        return bt_total_musicas;
    }

    public void setBt_total_musicas(JButton bt_total_musicas) {
        this.bt_total_musicas = bt_total_musicas;
    }

    public JButton getBt_total_usuarios() {
        return bt_total_usuarios;
    }

    public void setBt_total_usuarios(JButton bt_total_usuarios) {
        this.bt_total_usuarios = bt_total_usuarios;
    }

    public JButton getBt_voltar() {
        return bt_voltar;
    }

    public void setBt_voltar(JButton bt_voltar) {
        this.bt_voltar = bt_voltar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_top5mais = new javax.swing.JButton();
        bt_total_musicas = new javax.swing.JButton();
        bt_top5menos = new javax.swing.JButton();
        bt_total_usuarios = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(35, 35, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("ESTATÍSTICAS DO SISTEMA");

        bt_top5mais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_top5mais.setIconTextGap(5);
        bt_top5mais.setLabel("TOP 5 CURTIDAS");
        bt_top5mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_top5maisActionPerformed(evt);
            }
        });

        bt_total_musicas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_total_musicas.setText("TOTAL DE MÚSICAS");
        bt_total_musicas.setIconTextGap(5);
        bt_total_musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_total_musicasActionPerformed(evt);
            }
        });

        bt_top5menos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_top5menos.setText("TOP 5 DESCURTIDAS");
        bt_top5menos.setIconTextGap(5);
        bt_top5menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_top5menosActionPerformed(evt);
            }
        });

        bt_total_usuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_total_usuarios.setText("TOTAL DE USUÁRIOS");
        bt_total_usuarios.setIconTextGap(5);
        bt_total_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_total_usuariosActionPerformed(evt);
            }
        });

        bt_voltar.setBackground(new java.awt.Color(0, 0, 0));
        bt_voltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_voltar.setForeground(new java.awt.Color(250, 250, 250));
        bt_voltar.setText("VOLTAR");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_total_usuarios)
                        .addGap(139, 139, 139)
                        .addComponent(bt_total_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_top5mais, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(bt_top5menos)))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_top5mais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_top5menos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_total_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_total_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(bt_voltar)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_top5maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_top5maisActionPerformed
        // TODO add your handling code here:
        ADMTop5MaisPopUp top5Mais = new ADMTop5MaisPopUp(mainframe, true);
        top5Mais.setVisible(true);
    }//GEN-LAST:event_bt_top5maisActionPerformed

    private void bt_total_musicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_total_musicasActionPerformed
        // TODO add your handling code here:
        ADMTotalMusicaPopUp totalMusica = new ADMTotalMusicaPopUp(mainframe, true);
        totalMusica.setVisible(true);
    }//GEN-LAST:event_bt_total_musicasActionPerformed

    private void bt_top5menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_top5menosActionPerformed
        // TODO add your handling code here:
        ADMTop5MenosPopUp top5Menos = new ADMTop5MenosPopUp(mainframe, true);
        top5Menos.setVisible(true);
    }//GEN-LAST:event_bt_top5menosActionPerformed

    private void bt_total_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_total_usuariosActionPerformed
        // TODO add your handling code here:
        ADMTotalUserPopUp totalUser = new ADMTotalUserPopUp(mainframe, true);
        totalUser.setVisible(true);
    }//GEN-LAST:event_bt_total_usuariosActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMHOME_PANEL);
    }//GEN-LAST:event_bt_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_top5mais;
    private javax.swing.JButton bt_top5menos;
    private javax.swing.JButton bt_total_musicas;
    private javax.swing.JButton bt_total_usuarios;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public MainFrame getMainframe() {
        return mainframe;
    }

}
