/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.spotifei.Views.Panels;

import javax.swing.JButton;
import javax.swing.JLabel;
import net.spotifei.Views.MainFrame;

/**
 *
 * @author fengl
 */
public class HistoryPanel extends javax.swing.JPanel {

    private final MainFrame mainframe;
    
    public HistoryPanel(MainFrame mainframe) {
        initComponents();
        this.mainframe = mainframe;
    }

    public JButton getBt_curtidas() {
        return bt_curtidas;
    }

    public void setBt_curtidas(JButton bt_curtidas) {
        this.bt_curtidas = bt_curtidas;
    }

    public JButton getBt_deslikes() {
        return bt_deslikes;
    }

    public void setBt_deslikes(JButton bt_deslikes) {
        this.bt_deslikes = bt_deslikes;
    }

    public JButton getBt_home() {
        return bt_home;
    }

    public void setBt_home(JButton bt_home) {
        this.bt_home = bt_home;
    }

    public JButton getBt_pesquisa() {
        return bt_pesquisa;
    }

    public void setBt_pesquisa(JButton bt_pesquisa) {
        this.bt_pesquisa = bt_pesquisa;
    }

    public JButton getBt_playlist() {
        return bt_playlist;
    }

    public void setBt_playlist(JButton bt_playlist) {
        this.bt_playlist = bt_playlist;
    }

    public JButton getBt_top10() {
        return bt_top10;
    }

    public void setBt_top10(JButton bt_top10) {
        this.bt_top10 = bt_top10;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        bt_top10 = new javax.swing.JButton();
        bt_deslikes = new javax.swing.JButton();
        bt_curtidas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bt_playlist = new javax.swing.JButton();
        bt_home = new javax.swing.JButton();
        bt_pesquisa = new javax.swing.JButton();

        jMenu1.setText("jMenu1");
        jPopupMenu1.add(jMenu1);

        setBackground(new java.awt.Color(35, 35, 35));

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("HISTÓRICO");

        bt_top10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_top10.setText("TOP 10 ");
        bt_top10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_top10MouseClicked(evt);
            }
        });

        bt_deslikes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_deslikes.setText("DESLIKES");
        bt_deslikes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deslikesActionPerformed(evt);
            }
        });

        bt_curtidas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_curtidas.setText("CURTIDAS");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Aqui está seu histórico!");

        bt_playlist.setBackground(new java.awt.Color(0, 0, 0));
        bt_playlist.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_playlist.setForeground(new java.awt.Color(250, 250, 250));
        bt_playlist.setText("PLAYLIST");
        bt_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_playlistActionPerformed(evt);
            }
        });

        bt_home.setBackground(new java.awt.Color(0, 0, 0));
        bt_home.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_home.setForeground(new java.awt.Color(250, 250, 250));
        bt_home.setText("HOME");
        bt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_homeActionPerformed(evt);
            }
        });

        bt_pesquisa.setBackground(new java.awt.Color(0, 0, 0));
        bt_pesquisa.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_pesquisa.setForeground(new java.awt.Color(250, 250, 250));
        bt_pesquisa.setText("PESQUISA");
        bt_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(bt_top10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(bt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_deslikes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(570, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_top10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_deslikes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(444, Short.MAX_VALUE)
                    .addComponent(bt_home, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(45, 45, 45)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deslikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deslikesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_deslikesActionPerformed

    private void bt_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_playlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_playlistActionPerformed

    private void bt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_homeActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.HOME_PANEL);
    }//GEN-LAST:event_bt_homeActionPerformed

    private void bt_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.SEARCH_PANEL);
    }//GEN-LAST:event_bt_pesquisaActionPerformed

    private void bt_top10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_top10MouseClicked
        // TODO add your handling code here:
        
//        if(evt.isPopupTrigger()){
//            jPopupMenu1.show(this, 300, 400);
//            jPopupMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
//            jPopupMenu1.setForeground(new java.awt.Color(250, 250, 250));
//            jPopupMenu1.setToolTipText("Ultimas 10 músicas pesquisadas!");
//        }
    }//GEN-LAST:event_bt_top10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_curtidas;
    private javax.swing.JButton bt_deslikes;
    private javax.swing.JButton bt_home;
    private javax.swing.JButton bt_pesquisa;
    private javax.swing.JButton bt_playlist;
    private javax.swing.JButton bt_top10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

    public MainFrame getMainframe() {
        return mainframe;
    }

}
