/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.spotifei.Views.Panels;

import javax.swing.JButton;
import javax.swing.JLabel;

import net.spotifei.Controller.HistoryController;
import net.spotifei.Infrastructure.Container.AppContext;
import net.spotifei.Views.MainFrame;
import net.spotifei.Views.PopUps.DeslikedPopUp;
import net.spotifei.Views.PopUps.LikedPopUp;
import net.spotifei.Views.PopUps.MusicsPopUp;

/**
 *
 * @author fengl
 */
public class HistoryPanel extends javax.swing.JPanel {

    private final MainFrame mainframe;
    private final AppContext appContext;
    private final HistoryController historyController;
    private MusicsPopUp musicsPopUp;
    
    public HistoryPanel(MainFrame mainframe, AppContext appContext) {
        this.mainframe = mainframe;
        this.appContext = appContext;
        this.historyController = appContext.getHistoryController(this);
        initComponents();
    }

    public JButton getBt_curtidas() {
        return bt_curtidas;
    }

    public void setBt_curtidas(JButton bt_curtidas) {
        this.bt_curtidas = bt_curtidas;
    }

    public JButton getBt_deslikes() {
        return bt_deslikes;
    }

    public void setBt_deslikes(JButton bt_deslikes) {
        this.bt_deslikes = bt_deslikes;
    }

    public JButton getBt_top10() {
        return bt_top10;
    }

    public void setBt_top10(JButton bt_top10) {
        this.bt_top10 = bt_top10;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public MusicsPopUp getMusicsPopUp() {
        return musicsPopUp;
    }

    public void setMusicsPopUp(MusicsPopUp musicsPopUp) {
        this.musicsPopUp = musicsPopUp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        bt_top10 = new javax.swing.JButton();
        bt_deslikes = new javax.swing.JButton();
        bt_curtidas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");
        jPopupMenu1.add(jMenu1);

        setBackground(new java.awt.Color(35, 35, 35));

        jLabel4.setBackground(new java.awt.Color(250, 250, 250));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("HISTÓRICO");

        bt_top10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_top10.setText("TOP 10 ");
        bt_top10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_top10ActionPerformed(evt);
            }
        });

        bt_deslikes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_deslikes.setText("DESLIKES");
        bt_deslikes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deslikesActionPerformed(evt);
            }
        });

        bt_curtidas.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        bt_curtidas.setText("CURTIDAS");
        bt_curtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_curtidasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Aqui está seu histórico!");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_top10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(bt_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(bt_deslikes, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(323, 323, 323))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_top10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_deslikes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deslikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deslikesActionPerformed
        // TODO add your handling code here:
        historyController.showUserDislikedMusics();
    }//GEN-LAST:event_bt_deslikesActionPerformed

    private void bt_curtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_curtidasActionPerformed
        // TODO add your handling code here:
        historyController.showUserLikedMusics();
    }//GEN-LAST:event_bt_curtidasActionPerformed

    private void bt_top10ActionPerformed(java.awt.event.ActionEvent evt) {
//        Top10PopUp top10 = new Top10PopUp(mainframe, true);
//        top10.setVisible(true);
        historyController.showUserMostSearchedMusics();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_curtidas;
    private javax.swing.JButton bt_deslikes;
    private javax.swing.JButton bt_top10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

    public MainFrame getMainframe() {
        return mainframe;
    }

}
