/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.spotifei.Views.Panels.Admin;

import javax.swing.JButton;
import javax.swing.JLabel;

import net.spotifei.Infrastructure.Container.AppContext;
import net.spotifei.Views.MainFrame;

/**
 *
 * @author fengl
 */
public class ADMHomePanel extends javax.swing.JPanel {

    private final MainFrame mainframe;
    private final AppContext appContext;

    public ADMHomePanel(MainFrame mainframe, AppContext appContext) {
        this.appContext = appContext;
        this.mainframe = mainframe;
        initComponents();
    }

    public JButton getBt_cad_artista() {
        return bt_cad_artista;
    }

    public void setBt_cad_artista(JButton bt_cad_artista) {
        this.bt_cad_artista = bt_cad_artista;
    }

    public JButton getBt_cad_musica() {
        return bt_cad_musica;
    }

    public void setBt_cad_musica(JButton bt_cad_musica) {
        this.bt_cad_musica = bt_cad_musica;
    }

    public JButton getBt_consulta_usuario() {
        return bt_consulta_usuario;
    }

    public void setBt_consulta_usuario(JButton bt_consulta_usuario) {
        this.bt_consulta_usuario = bt_consulta_usuario;
    }

    public JButton getBt_excluir_musica() {
        return bt_excluir_musica;
    }

    public void setBt_excluir_musica(JButton bt_excluir_musica) {
        this.bt_excluir_musica = bt_excluir_musica;
    }

    public JButton getBt_sistema() {
        return bt_sistema;
    }

    public void setBt_sistema(JButton bt_sistema) {
        this.bt_sistema = bt_sistema;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_cad_musica = new javax.swing.JButton();
        bt_excluir_musica = new javax.swing.JButton();
        bt_cad_artista = new javax.swing.JButton();
        bt_consulta_usuario = new javax.swing.JButton();
        bt_sistema = new javax.swing.JButton();

        setBackground(new java.awt.Color(35, 35, 35));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("ADMINISTRADOR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("BEM-VINDO ADM!");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("> O QUE DESEJA FAZER?");

        bt_cad_musica.setBackground(new java.awt.Color(0, 0, 0));
        bt_cad_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cad_musica.setForeground(new java.awt.Color(250, 250, 250));
        bt_cad_musica.setText("Cadastrar Músicas");
        bt_cad_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cad_musicaActionPerformed(evt);
            }
        });

        bt_excluir_musica.setBackground(new java.awt.Color(0, 0, 0));
        bt_excluir_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_excluir_musica.setForeground(new java.awt.Color(250, 250, 250));
        bt_excluir_musica.setText("Excluir Músicas");
        bt_excluir_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_musicaActionPerformed(evt);
            }
        });

        bt_cad_artista.setBackground(new java.awt.Color(0, 0, 0));
        bt_cad_artista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cad_artista.setForeground(new java.awt.Color(250, 250, 250));
        bt_cad_artista.setText("Cadastrar Artistas");
        bt_cad_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cad_artistaActionPerformed(evt);
            }
        });

        bt_consulta_usuario.setBackground(new java.awt.Color(0, 0, 0));
        bt_consulta_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_consulta_usuario.setForeground(new java.awt.Color(250, 250, 250));
        bt_consulta_usuario.setText("Consultar Usuários");
        bt_consulta_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consulta_usuarioActionPerformed(evt);
            }
        });

        bt_sistema.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_sistema.setForeground(new java.awt.Color(0, 204, 102));
        bt_sistema.setText("Estátisticas do Sistema");
        bt_sistema.setBorderPainted(false);
        bt_sistema.setContentAreaFilled(false);
        bt_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_excluir_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_consulta_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cad_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cad_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(15, 15, 15)
                .addComponent(bt_cad_musica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_excluir_musica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cad_artista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_consulta_usuario)
                .addGap(76, 76, 76)
                .addComponent(bt_sistema)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cad_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cad_musicaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMREGMUSIC_PANEL);
    }//GEN-LAST:event_bt_cad_musicaActionPerformed

    private void bt_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sistemaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMESTATISTICS_PANEL);
    }//GEN-LAST:event_bt_sistemaActionPerformed

    private void bt_consulta_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consulta_usuarioActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMCONUSER_PANEL);
    }//GEN-LAST:event_bt_consulta_usuarioActionPerformed

    private void bt_excluir_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_musicaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMDELMUSIC_PANEL);
    }//GEN-LAST:event_bt_excluir_musicaActionPerformed

    private void bt_cad_artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cad_artistaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMCADARTIST_PANEL);
    }//GEN-LAST:event_bt_cad_artistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cad_artista;
    private javax.swing.JButton bt_cad_musica;
    private javax.swing.JButton bt_consulta_usuario;
    private javax.swing.JButton bt_excluir_musica;
    private javax.swing.JButton bt_sistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public MainFrame getMainframe() {
        return mainframe;
    }

}
