
package net.spotifei.Views.Panels.Admin;

//imports
import net.spotifei.Infrastructure.Container.AppContext;
import net.spotifei.Views.MainFrame;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author fengl
 */
public class ADMHomePanel extends javax.swing.JPanel {

    private final MainFrame mainframe;
    private final AppContext appContext;

    /**
     * Construtor da classe `ADMHomePanel`.
     *
     * @param mainframe A instância da janela principal (`MainFrame`).
     * @param appContext O contexto da aplicação.
     */
    public ADMHomePanel(MainFrame mainframe, AppContext appContext) {
        this.appContext = appContext;
        this.mainframe = mainframe;
        initComponents();
    }

    // Métodos Getters e Setters para os componentes visuais.
    public JButton getBt_cad_artista() {
        return bt_cad_artista;
    }

    public void setBt_cad_artista(JButton bt_cad_artista) {
        this.bt_cad_artista = bt_cad_artista;
    }

    public JButton getBt_cad_musica() {
        return bt_cad_musica;
    }

    public void setBt_cad_musica(JButton bt_cad_musica) {
        this.bt_cad_musica = bt_cad_musica;
    }

    public JButton getBt_consulta_usuario() {
        return bt_consulta_usuario;
    }

    public void setBt_consulta_usuario(JButton bt_consulta_usuario) {
        this.bt_consulta_usuario = bt_consulta_usuario;
    }

    public JButton getBt_excluir_musica() {
        return bt_excluir_musica;
    }

    public void setBt_excluir_musica(JButton bt_excluir_musica) {
        this.bt_excluir_musica = bt_excluir_musica;
    }

    public JButton getBt_sistema() {
        return bt_sistema;
    }

    public void setBt_sistema(JButton bt_sistema) {
        this.bt_sistema = bt_sistema;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    /**
     * Método privado para inicializar e configurar os componentes visuais do painel.
     */
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_cad_musica = new javax.swing.JButton();
        bt_excluir_musica = new javax.swing.JButton();
        bt_cad_artista = new javax.swing.JButton();
        bt_consulta_usuario = new javax.swing.JButton();
        bt_sistema = new javax.swing.JButton();

        setBackground(new java.awt.Color(35, 35, 35));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("ADMINISTRADOR");
        jLabel1.setAlignmentX(CENTER_ALIGNMENT);


        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("BEM-VINDO ADM!");
        jLabel2.setAlignmentX(CENTER_ALIGNMENT);


        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("> O QUE DESEJA FAZER?");
        jLabel3.setAlignmentX(CENTER_ALIGNMENT);


        bt_cad_musica.setMaximumSize(new Dimension(300, bt_cad_musica.getPreferredSize().height));
        bt_cad_musica.setBackground(new java.awt.Color(0, 0, 0));
        bt_cad_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cad_musica.setForeground(new java.awt.Color(250, 250, 250));
        bt_cad_musica.setText("Cadastrar Músicas");
        bt_cad_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cad_musicaActionPerformed(evt);
            }
        });
        bt_cad_musica.setAlignmentX(CENTER_ALIGNMENT);


        bt_excluir_musica.setMaximumSize(new Dimension(300, bt_excluir_musica.getPreferredSize().height));
        bt_excluir_musica.setBackground(new java.awt.Color(0, 0, 0));
        bt_excluir_musica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_excluir_musica.setForeground(new java.awt.Color(250, 250, 250));
        bt_excluir_musica.setText("Excluir Músicas");
        bt_excluir_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_musicaActionPerformed(evt);
            }
        });
        bt_excluir_musica.setAlignmentX(CENTER_ALIGNMENT);


        bt_cad_artista.setMaximumSize(new Dimension(300, bt_cad_artista.getPreferredSize().height));
        bt_cad_artista.setBackground(new java.awt.Color(0, 0, 0));
        bt_cad_artista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cad_artista.setForeground(new java.awt.Color(250, 250, 250));
        bt_cad_artista.setText("Cadastrar Artistas");
        bt_cad_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cad_artistaActionPerformed(evt);
            }
        });
        bt_cad_artista.setAlignmentX(CENTER_ALIGNMENT);


        bt_consulta_usuario.setMaximumSize(new Dimension(300, bt_consulta_usuario.getPreferredSize().height));
        bt_consulta_usuario.setBackground(new java.awt.Color(0, 0, 0));
        bt_consulta_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_consulta_usuario.setForeground(new java.awt.Color(250, 250, 250));
        bt_consulta_usuario.setText("Consultar Usuários");
        bt_consulta_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consulta_usuarioActionPerformed(evt);
            }
        });
        bt_consulta_usuario.setAlignmentX(CENTER_ALIGNMENT);


        bt_sistema.setMaximumSize(new Dimension(300, bt_sistema.getPreferredSize().height));
        bt_sistema.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bt_sistema.setForeground(new java.awt.Color(0, 109, 170));
        bt_sistema.setText("Estátisticas do Sistema");
        bt_sistema.setBorderPainted(false);
        bt_sistema.setContentAreaFilled(false);
        bt_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sistemaActionPerformed(evt);
            }
        });
        bt_sistema.setAlignmentX(CENTER_ALIGNMENT);

        bt_cad_genero = new javax.swing.JButton();
        bt_cad_genero.setMaximumSize(new Dimension(300, bt_cad_genero.getPreferredSize().height));
        bt_cad_genero.setBackground(new java.awt.Color(0, 0, 0));
        bt_cad_genero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bt_cad_genero.setForeground(new java.awt.Color(250, 250, 250));
        bt_cad_genero.setText("Cadastrar Gênero");
        bt_cad_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cad_generoActionPerformed();
            }
        });
        bt_cad_genero.setAlignmentX(CENTER_ALIGNMENT);

        JButton bt_sair = new JButton("Deslogar");
        bt_sair.setFont(new java.awt.Font("Segoe UI Black", 1, 18));
        bt_sair.setAlignmentX(CENTER_ALIGNMENT);
        bt_sair.addActionListener(this::bt_sairActionPerformed);
        bt_sair.setMaximumSize(new Dimension(200, 50));
        bt_sair.setBackground(Color.gray);
        bt_sair.setForeground(Color.black);
        bt_cad_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });

        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        setAlignmentX(CENTER_ALIGNMENT);

        add(Box.createVerticalGlue());
        add(jLabel1);
        add(Box.createVerticalStrut(10));
        add(jLabel2);
        add(Box.createVerticalStrut(10));
        add(jLabel3);
        add(Box.createVerticalStrut(50));
        add(bt_cad_musica);
        add(Box.createVerticalStrut(10));
        add(bt_excluir_musica);
        add(Box.createVerticalStrut(10));
        add(bt_cad_artista);
        add(Box.createVerticalStrut(10));
        add(bt_consulta_usuario);
        add(Box.createVerticalStrut(10));
        add(bt_cad_genero);
        add(Box.createVerticalStrut(30));
        add(bt_sistema);
        add(Box.createVerticalStrut(30));
        add(bt_sair);
        add(Box.createVerticalGlue());


    }

    /**
     * Método acionado pelo botão "Cadastrar Músicas".
     *
     * @param evt O evento de ação.
     */
    private void bt_cad_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cad_musicaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMREGMUSIC_PANEL);
    }//GEN-LAST:event_bt_cad_musicaActionPerformed

    /**
     * Método acionado pelo botão "Estatísticas do Sistema".
     *
     * @param evt O evento de ação.
     */
    private void bt_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sistemaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMESTATISTICS_PANEL);
    }//GEN-LAST:event_bt_sistemaActionPerformed

    /**
     * Método acionado pelo botão "Consultar Usuários".
     *
     * @param evt O evento de ação.
     */
    private void bt_consulta_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consulta_usuarioActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMCONUSER_PANEL);
    }//GEN-LAST:event_bt_consulta_usuarioActionPerformed

    /**
     * Método acionado pelo botão "Excluir Músicas".
     *
     * @param evt O evento de ação.
     */
    private void bt_excluir_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_musicaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMDELMUSIC_PANEL);
    }//GEN-LAST:event_bt_excluir_musicaActionPerformed

    /**
     * Método acionado pelo botão "Cadastrar Artistas".
     *
     * @param evt O evento de ação.
     */
    private void bt_cad_artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cad_artistaActionPerformed
        // TODO add your handling code here:
        mainframe.setPanel(MainFrame.ADMCADARTIST_PANEL);
    }//GEN-LAST:event_bt_cad_artistaActionPerformed

    /**
     * Método acionado pelo botão "Deslogar".
     *
     * @param evt O evento de ação.
     */
    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt){
        mainframe.setPanel(MainFrame.LOGIN_PANEL);
    }

    /**
     * Método acionado pelo botão "Cadastrar Gênero".
     *
     */
    private void bt_cad_generoActionPerformed(){
        mainframe.setPanel(MainFrame.ADMCADGENRE_PANEL);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cad_artista;
    private javax.swing.JButton bt_cad_musica;
    private javax.swing.JButton bt_consulta_usuario;
    private javax.swing.JButton bt_excluir_musica;
    private javax.swing.JButton bt_sistema;
    private JButton bt_cad_genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter para a instância do `MainFrame`.
     *
     * @return A instância do `MainFrame`.
     */
    public MainFrame getMainframe() {
        return mainframe;
    }

}





